WebRaoVat/WebRaoVat/Models/PostCategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCategory
    {
        public PostCategory()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryAlias { get; set; }
        public int ModUserId { get; set; }
        public string CustomAds { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}

WebRaoVat/WebRaoVat/Controllers/PostCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRaoVat.Models;

namespace WebRaoVat.Controllers
{
    public class PostCategoryController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /PostCategory/

        public ActionResult Index()
        {
            var postcategories = db.PostCategories.Include(p => p.UserProfile);
            return View(postcategories.ToList());
        }

        //
        // GET: /PostCategory/Details/5
       
        public ActionResult Details(int CatId = 0, int page=1, int PageSize=10,int SortBy=0, bool IsAsc=true, string Search=null)
        {
            if (CatId==0)
                return RedirectToAction("Index", "Post", new { Search = Search });
            // tim kiem truoc khi sort, gioi han so data
            var PostList = db.PostCategories.Find(CatId);
            if (PostList == null)
            {
                return HttpNotFound();
            }
            IEnumerable<Post> PostListFiltered;
            try
            {
                PostListFiltered = PostList.Posts.Where(
                                                                  p => Search == null
                                                                    || p.Title.Contains(Search)
                                                                    || p.ShortDescription.Contains(Search)
                                                                    || p.Detail.Contains(Search)
                                                                    || p.TitleAlias.Contains(Search));
            }
            catch (System.NullReferenceException e) //exeption xay ra khi 1 trong cac field == null 
            {       
                    return HttpNotFound();
            };

            //khong tim thay category, return 404

            
            // xu ly sap xep bai post 
            switch (SortBy)
            {
                case 1:
                    PostListFiltered = IsAsc ? PostListFiltered.OrderBy(p => p.Title) : PostListFiltered.OrderByDescending(p => p.Title);
                    break;
                case 2:
                    PostListFiltered = IsAsc ? PostListFiltered.OrderBy(p => p.Created) : PostListFiltered.OrderByDescending(p => p.Created);
                    break;
                case 3:
                    PostListFiltered = IsAsc ? PostListFiltered.OrderBy(p => p.HitCount) : PostListFiltered.OrderByDescending(p => p.HitCount);
                    break;
                case 4:
                    PostListFiltered = IsAsc ? PostListFiltered.OrderBy(p => p.Price) : PostListFiltered.OrderByDescending(p => p.Price);
                    break;
                default:
                    PostListFiltered = IsAsc ? PostListFiltered.OrderBy(p => p.PostId) : PostListFiltered.OrderByDescending(p => p.PostId);
                    break;
            }
            //paging , numitem = pagesize
            

            ViewBag.CatId = CatId;
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = PageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)PostListFiltered.Count() / PageSize);
            ViewBag.SortBy = SortBy;
            ViewBag.IsAsc = IsAsc;
            ViewBag.Search = Search;
            ViewBag.CategoryName = PostList.CategoryName;
            PostListFiltered = PostListFiltered.Skip((page - 1) * PageSize).Take(PageSize).ToList();

            return View(PostListFiltered.ToList());
        }

        //
        // GET: /PostCategory/Create

        public ActionResult Create()
        {
            ViewBag.ModUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /PostCategory/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostCategory postcategory)
        {
            if (ModelState.IsValid)
            {
                db.PostCategories.Add(postcategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ModUserId = new SelectList(db.UserProfiles, "UserId", "UserName", postcategory.ModUserId);
            return View(postcategory);
        }

        //
        // GET: /PostCategory/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PostCategory postcategory = db.PostCategories.Find(id);
            if (postcategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ModUserId = new SelectList(db.UserProfiles, "UserId", "UserName", postcategory.ModUserId);
            return View(postcategory);
        }

        //
        // POST: /PostCategory/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PostCategory postcategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(postcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ModUserId = new SelectList(db.UserProfiles, "UserId", "UserName", postcategory.ModUserId);
            return View(postcategory);
        }

        //
        // GET: /PostCategory/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PostCategory postcategory = db.PostCategories.Find(id);
            if (postcategory == null)
            {
                return HttpNotFound();
            }
            return View(postcategory);
        }

        //
        // POST: /PostCategory/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PostCategory postcategory = db.PostCategories.Find(id);
            db.PostCategories.Remove(postcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebRaoVat/WebRaoVat/Views/PostCategory/Create.cshtml
@model WebRaoVat.Models.PostCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PostCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryId)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryName)
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryAlias)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryAlias)
            @Html.ValidationMessageFor(model => model.CategoryAlias)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModUserId, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ModUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.ModUserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomAds)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomAds)
            @Html.ValidationMessageFor(model => model.CustomAds)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/PostCategory/Delete.cshtml
@model WebRaoVat.Models.PostCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PostCategory</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CategoryId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CategoryName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CategoryAlias)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryAlias)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CustomAds)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomAds)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebRaoVat/WebRaoVat/Views/PostCategory/Details.cshtml
@model IEnumerable<WebRaoVat.Models.Post>
@* function tao link cho viec sap xep tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper sortLink(string name, int id)
{  
  @* <a href="@Url.Action("Index", "Post", new { CatId= ViewBag.CatId, SortBy = id, PageSize= ViewBag.PageSize,Search=ViewBag.Search, IsAsc = (id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower() })">@name</a> *@
  @:  <option value="/PostCategory/Details?CatId=@ViewBag.CatId&SortBy=@id&PageSize=@ViewBag.PageSize&Search=@ViewBag.Search&IsAsc=@((id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower())">@name</option>
}
@* function tao link cho viec phan trang, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper buildLinks(int start, int end, string innerContent)
{
     for (int i = start; i <= end; i++)
     {
         <a class="@(i == ViewBag.CurrentPage ? "current" : "")" href="@Url.Action("Details", "PostCategory", new { CatId= ViewBag.CatId, SortBy =ViewBag.SortBy, PageSize= ViewBag.PageSize, IsAsc=ViewBag.IsAsc, Search=ViewBag.Search ,page = i })">@(innerContent ?? i.ToString())</a>  
     }
     
}
@* function hien thi pagelink hop ly khi co qua nhieu trang vd 1.....5.current.7....100, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper pageLinks()
{  
    const int maxPages = 11;
     
    if (ViewBag.TotalPages <= maxPages)
    {
        @buildLinks(1, (int)ViewBag.TotalPages, null)
        return;
    }
 
    int pagesAfter = ViewBag.TotalPages - ViewBag.CurrentPage; // Number of pages after current
    int pagesBefore = ViewBag.CurrentPage - 1; // Number of pages before current
 
    if (pagesAfter <= 4)
    {
        @buildLinks(1, 1, null) // Show 1st page
 
        int pageSubset = ViewBag.TotalPages - maxPages - 1 > 1 ? ViewBag.TotalPages - maxPages - 1 : 2;
        @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
        @buildLinks(ViewBag.TotalPages - maxPages + 3, ViewBag.TotalPages, null) // Show last pages
 
        return; // Exit
    }
 
    if (pagesBefore <= 4)
    {
       @buildLinks(1, maxPages - 2, null) // Show 1st pages
 
 
       int pageSubset = maxPages + 2 < ViewBag.TotalPages ? maxPages + 2 : ViewBag.TotalPages - 1;
       @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
       @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
 
        return; // Exit
 
    }
 
    if (pagesAfter > 4)
    {
        @buildLinks(1, 1, null) // Show 1st pages
 
        int pageSubset1 = ViewBag.CurrentPage - 7 > 1 ? ViewBag.CurrentPage - 7 : 2;
        int pageSubset2 = ViewBag.CurrentPage + 7 < ViewBag.TotalPages ? ViewBag.CurrentPage + 7 : ViewBag.TotalPages - 1;
 
        @buildLinks(pageSubset1, pageSubset1, pageSubset1 == ViewBag.CurrentPage - 4 ? null : "...") // Show 1st page subset (...)
 
        @buildLinks(ViewBag.CurrentPage - 3, ViewBag.CurrentPage + 3, null) // Show middle pages
         // Show 2nd page subset (...)
        // only show ... if page is contigous to the previous one.
        @buildLinks(pageSubset2, pageSubset2, pageSubset2 ==  ViewBag.CurrentPage + 4 ? null : "...")
        @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
         return; // Exit
 
    }    
}


@{
    ViewBag.Title = ViewBag.CategoryName;
}
	<div id="main-content">
				<div class="show-posts">
					<div class= "show-posts-header">
						<div class="category-header">
							@ViewBag.CategoryName
						</div>
						<div class="sort-posts">
							<span>Sắp xếp theo:</span>
							<select onchange="if (this.selectedIndex) {location = this.options[this.selectedIndex].value;}">
                                @sortLink("Thông thường", 0)
                                @sortLink("Tiêu đề", 1)
                                @sortLink("Ngày tạo", 2)
                                @sortLink("Lượt xem", 3)
                                @sortLink("Giá", 4)
							</select>
						</div>
					</div> <!--end of show-posts-header-->
                    @foreach (var item in Model) 
                    {
                         <a href="/Post/Details?id=@item.PostId">

                           <div class="post-item">

                               <div class="post-content-wrapper @(item.PostType==1?"vip": "") ">

                                   <div class="post-header">
                                       @item.Title
                                  </div>
                                  <div class="clear"></div>
					                    	<img src="/Content/Upload/Images/@item.Thumbnail" class="post-image"/>
                                   <div class="post-description-wrapper">
                                       <div class="post-content">
                                           @item.ShortDescription
                                       </div>
                                       <div class = "clear"></div>	
                                       <div class="description-i">
								            <span class="description-i-caption">
									            Giá:
								            </span>
								            <span class="description-i-value">
									            @(item.Price==null ? "Thỏa Thuận" : item.Price)
								            </span>
                                        </div><!-- end of description-i -->
                                        <div class="description-i">
								            <span class="description-i-caption">
									            Quận/Huyện:
								            </span>
								            <span class="description-i-value">
									            @item.Zone.ZoneName
								            </span>									
							            </div><!-- end of description-i -->
						            	<!--date-->
							            <span class="published-date">
								            @(item.Created==null? "1/1/2001": item.Created.Value.ToString("dd/MM/yyyy"))
							            </span>


							            
                                   </div><!-- end of post-description-wrapper -->
                               </div><!-- end of post-content-wrapper -->


                            </div> <!--end of postitem-->

                    </a>
                           
                }
        </div> <!--end of show-postsr-->
<div class="pagination">
Trang: @pageLinks()       
</div>
</div> <!--end of main-content-->
		<div class="adswrapper">
			<div class="ads">
					Quảng Cáo
			</div>
		</div>


			<div id="footer" style="margin-left:10px;">	
				<div class="footer_container">
					<div class="addr_footer">
						<span class="footer_head">Liên hệ</span>
							<a>Địa chỉ: Hòa Thành, Tây Ninh</a>
							<a>Số điện thoại: 0123456789</a>
					</div>
					<div class="info_footer">
						<span class="footer_head">Thông tin cho bạn</span>
							<a href="http://www.nhanh60s.vn/">Quy định đăng tin</a>
							<a href="http://www.nhanh60s.vn/">Điều khoản</a>
							<a href="http://www.nhanh60s.vn/">Chính sách</a>
							<a href="http://www.nhanh60s.vn" >Kinh nghiệm đăng tin</a>
					</div>
					<div class="about_footer">
						<span class="footer_head">Về chúng tôi</span>
							<a href="http://www.nhanh60s.vn/">Giới thiệu</a>
							<a href="http://www.nhanh60s.vn/">Mục tiêu</a>
							<a href="http://www.nhanh60s.vn/tuyendung">Tuyển dụng</a>
					</div>
					
					<div class="register_footer">
						<span class="footer_head">Chứng nhận</span>
						<a href="http://online.gov.vn/HomePage/" target="_blank">
							<img class="bct" src="/Content/bct.png">
						</a>
					</div>
					
					<div class="clear_float"></div>
				</div>
				<hr>
					<p style="color: #808080;">
						Bản quyền của <a href="http://Nhanh60s.vn" style="color: #66FFCC">Nhanh60s</a> |  WWW.NHANH60S.VN © 2015  </p>
			</div>

WebRaoVat/WebRaoVat/Views/PostCategory/Edit.cshtml
@model WebRaoVat.Models.PostCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PostCategory</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryId)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryName)
            @Html.ValidationMessageFor(model => model.CategoryName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CategoryAlias)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CategoryAlias)
            @Html.ValidationMessageFor(model => model.CategoryAlias)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModUserId, "UserProfile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ModUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.ModUserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomAds)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomAds)
            @Html.ValidationMessageFor(model => model.CustomAds)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/PostCategory/Index.cshtml
@model IEnumerable<WebRaoVat.Models.PostCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryAlias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomAds)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryAlias)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomAds)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>