WebRaoVat/WebRaoVat/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Post
    {
        public Post()
        {
            this.PostImages = new HashSet<PostImage>();
        }
    
        public int PostId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Title { get; set; }
        public string TitleAlias { get; set; }
        public int CategoryId { get; set; }
        public string ShortDescription { get; set; }

        [AllowHtml]
        public string Detail { get; set; }
        public string Price { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<byte> PostType { get; set; }
        public Nullable<int> HitCount { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual PostCategory PostCategory { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ICollection<PostImage> PostImages { get; set; }
    }
}

WebRaoVat/WebRaoVat/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using WebRaoVat.Filters;
using WebRaoVat.Models;

namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class PostController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index(int CatId = 0,int page = 1, int PageSize = 5, int SortBy = 1, bool IsAsc = true, string Search = null)
        {
            if (CatId != 0) // user want to view specific category's post
                return RedirectToAction("PostCategory", "Details", new { CatId = CatId });

          /*  var posts = db.Posts.Include(p => p.PostCategory).Include(p => p.UserProfile).Include(p => p.Zone);*/
            //tim kiem post
            var posts = db.Posts.Where(
                                    p => Search == null
                                    || p.Title.Contains(Search)
                                    || p.ShortDescription.Contains(Search)
                                    || p.Detail.Contains(Search)
                                    || p.TitleAlias.Contains(Search));
            IEnumerable<Post> postlist;
            switch (SortBy)
            {
                case 1:
                    postlist = IsAsc ? posts.OrderBy(p => p.Title) : posts.OrderByDescending(p => p.Title);
                    break;
                case 2:
                    postlist = IsAsc ? posts.OrderBy(p => p.Created) : posts.OrderByDescending(p => p.Created);
                    break;
                case 3:
                    postlist = IsAsc ? posts.OrderBy(p => p.HitCount) : posts.OrderByDescending(p => p.HitCount);
                    break;
                case 4:
                    postlist = IsAsc ? posts.OrderBy(p => p.Price) : posts.OrderByDescending(p => p.Price);
                    break;
                default:
                    postlist = IsAsc ? posts.OrderBy(p => p.PostId) : posts.OrderByDescending(p => p.PostId);
                    break;
            }
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = PageSize;
            ViewBag.TotalPages = (int)Math.Ceiling((double)postlist.Count() / PageSize);
            ViewBag.SortBy = SortBy;
            ViewBag.IsAsc = IsAsc;
            ViewBag.Search = Search;
            postlist = postlist.Skip((page - 1) * PageSize).Take(PageSize).ToList();
            return View(postlist.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            
            Post post = db.Posts.Find(id);
            
            if (post == null)
            {
                return HttpNotFound();
            }
            if ((WebSecurity.CurrentUserId == post.UserId )|| (WebSecurity.CurrentUserName =="admin"))
                ViewBag.Editable = 1;
            else
                ViewBag.Editable = 0;
            db.Entry(post).State = EntityState.Modified;
            post.HitCount = ((post.HitCount != null) ? post.HitCount + 1 : 1);
            db.SaveChanges();
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.PostCategories, "CategoryId", "CategoryName");
            ViewBag.UserId = WebSecurity.CurrentUserId;
            ViewBag.ZoneId = new SelectList(db.Zones, "ZoneId", "ZoneName");
            ViewBag.ShortDescription = "";
            ViewBag.Detail = "";
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
          string[] images_links=null;
          if (Request["images"] != null)
             images_links = Request["images"].ToString().Split(':');

           if (ModelState.IsValid)
                {
                    //first link is thumbnail;
                    if (!String.IsNullOrEmpty(images_links[0]))
                        post.Thumbnail = images_links[0];
                    post.TitleAlias = "sample-alias"; //processing alias here
                    post.Created = System.DateTime.Now;
                    post.Active = true;
                    post.HitCount = 1;
                    if (WebSecurity.CurrentUserName != "admin" && post.CategoryId == 14)
                        post.CategoryId = 12;
                    db.Posts.Add(post);

                            for (int i = 1; i < images_links.Length; i++) //skip first image
                            {
                                if (!String.IsNullOrEmpty(images_links[i]))
                                {
                                    PostImage post_image;
                                    post_image = new PostImage();
                                    post_image.ImageURL = images_links[i].ToString();
                                    post_image.PostId = post.PostId;
                                    db.PostImages.Add(post_image);
                                }
                            }
                    
                        db.SaveChanges();
                    return RedirectToAction("Details", new { id = post.PostId });
           }
           ViewBag.ShortDescription = post.ShortDescription;
           ViewBag.Detail = post.Detail;
            ViewBag.CategoryId = new SelectList(db.PostCategories, "CategoryId", "CategoryName", post.CategoryId);
            ViewBag.UserId = ViewBag.UserId = WebSecurity.CurrentUserId;
            ViewBag.ZoneId = new SelectList(db.Zones, "ZoneId", "ZoneName", post.ZoneId);
            if (images_links.Length>0 && images_links[0]!="")
             ViewBag.Images = images_links;
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null || (WebSecurity.CurrentUserId!=post.UserId && WebSecurity.CurrentUserName!="admin")) //only user authorized can edit
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.PostCategories, "CategoryId", "CategoryName", post.CategoryId);
            ViewBag.ZoneId = new SelectList(db.Zones, "ZoneId", "ZoneName", post.ZoneId);
            List<string> ImagesCollection = new List<string>();
            ImagesCollection.Add(post.Thumbnail);
            ImagesCollection.AddRange(post.PostImages.Select(a => a.ImageURL).ToList());
            ViewBag.Images = ImagesCollection.ToArray();
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {       
            string[] images_links = null;
            if (Request["images"] != null)
                images_links = Request["images"].ToString().Split(':');

            if(post.UserId!=WebSecurity.CurrentUserId)
                return HttpNotFound();
//            if (ModelState.IsValid)
//            {
                //first link is thumbnail;
                if (!String.IsNullOrEmpty(images_links[0]))
                    post.Thumbnail = images_links[0];
                post.TitleAlias = "sample-alias"; //processing alias here
                if (WebSecurity.CurrentUserName != "admin" && post.CategoryId == 14)
                    post.CategoryId = 12;
                db.Entry(post).State = EntityState.Modified;

                for (int i = 1; i < images_links.Length; i++) //skip first image
                {
                    if (!String.IsNullOrEmpty(images_links[i]))
                    {
                        PostImage post_image;
                        post_image = new PostImage();
                        post_image.ImageURL = images_links[i].ToString();
                        post_image.PostId = post.PostId;
                        db.PostImages.Add(post_image);
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Details", new { id = post.PostId });
    //        }
/*
            ViewBag.CategoryId = new SelectList(db.PostCategories, "CategoryId", "CategoryName", post.CategoryId);
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserId);
            ViewBag.ZoneId = new SelectList(db.Zones, "ZoneId", "ZoneName", post.ZoneId);

            if (images_links != null)
                ViewBag.Images = images_links;
            
            return View(post);
 * */
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
/*            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);*/ 
            // not necessary to confirm, only user who created post or admin/mod can delete
            //first step, only user created post can delete
            if ((WebSecurity.CurrentUserId == post.UserId) ||(WebSecurity.CurrentUserName == "admin" ))
            {
     /*           IEnumerable<PostImage> post_images = db.PostImages.Where(t => t.PostId == post.PostId);
                foreach (PostImage image in post_images)
                {
                    db.PostImages.Remove(image);
                    db.SaveChanges();
                }*/
                db.Posts.Remove(post);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

WebRaoVat/WebRaoVat/Views/Post/Create.cshtml
@model WebRaoVat.Models.Post

@{
    ViewBag.Title = "Create";
}

<script src="/Scripts/nicEdit.js" type="text/javascript"></script>
<script type="text/javascript">
bkLib.onDomLoaded(function() {
    new nicEditor({fullPanel : true, iconsPath: '/Content/Images/nicEditorIcons.gif' }).panelInstance('Detail');
});
</script>


<h2>Đăng tin rao vặt</h2>

<form action="/post/create" class="aspform" method="post" id="createform" name="createform" novalidate="novalidate">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-field">
            <input type="hidden" name="UserId" value="@ViewBag.UserId" />
        </div>

        <br /> Tiêu đề tin<br />
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Title, new { maxlength="200" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <br /> Thể loại<br />
        <div class="editor-field">
            @Html.DropDownList("CategoryId", String.Empty)
            @Html.ValidationMessageFor(model => model.CategoryId)
        </div>
            
        <br /> Mô tả ngắn gọn<br />
        <textarea id="ShortDescription" name="ShortDescription" form="createform" rows="4" cols="60" maxlength="200">@ViewBag.ShortDescription</textarea>
				<br />
       <br /> Mô tả chi tiết<br />
       <textarea  id="Detail" name="Detail" form="createform" rows="20" cols="60" maxlength="500">@ViewBag.Detail</textarea>

        <br /> Giá<br />
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Price, new { maxlength="20" })
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <br /> Quận/Huyện<br />
        <div class="editor-field">
            @Html.DropDownList("ZoneId", String.Empty)
            @Html.ValidationMessageFor(model => model.ZoneId)
        </div>
				
        <br /> Loại tin post:<br />
    @*      <div class="editor-field">
            @Html.EditorFor(model => model.PostType)
            @Html.ValidationMessageFor(model => model.PostType)
        </div>
    *@
    <div class="editor-field">
            <select name="PostType" id ="PostType">
               <option value="0">Bình Thường</option>
               <option value="1">Vip</option>
            </select>
        </div>
				
				<br />
        <p>
            <input type="submit" value="Đăng Tin" />
        </p>
</form>

<form action="/File/Upload" class ="dropzone" id="UploadImage">
		<ul>
		<h3>Chọn upload theo thứ tự:</h3>
		<li>Ảnh đại diện cho bài viết</li>
		<li>Ảnh sản phẩm 1</li>
		<li>Ảnh sản phẩm 2</li>
		<li>...(Tối đa 1 ảnh đại diện và 5 ảnh sản phẩm)</li>
		</ul>
</form>
	
            @{
        //        string[] fields = { "ThumbnailUrl", "PreviewImage1", "PreviewImage2", "PreviewImage3", "PreviewImage4", "PreviewImage5" };
                string form_id = "UploadImage";
                string form_contain_fields_id = "createform";
                int num_images = 6;
            }
    @if (ViewBag.Images != null)
    {
        @ViewsUtilities.EditFile(form_id, form_contain_fields_id, num_images, ViewBag.Images);
    }
    else
    {
        @ViewsUtilities.Upload_File(form_id, form_contain_fields_id, num_images);
    }
    
   

<div class="preview-content">
    @ViewBag.HtmlContent
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/Post/Delete.cshtml
@model WebRaoVat.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Created)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Created)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TitleAlias)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TitleAlias)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostCategory.CategoryName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostCategory.CategoryName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ShortDescription)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ShortDescription)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Detail)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Detail)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Zone.ZoneName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Zone.ZoneName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Active)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Active)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HitCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HitCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Thumbnail)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Thumbnail)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebRaoVat/WebRaoVat/Views/Post/Details.cshtml
@model WebRaoVat.Models.Post

@{
    ViewBag.Title = Model.Title;
    string product_link = "http://nhanh60s.vn/post/details/" + Model.PostId.ToString();
}

@ViewsUtilities.FacebookInit()

<div id="main-content">
    <div id="show-post-detail">
         <div class= "post-detail-header">
			<div class="category-header">
				@Model.PostCategory.CategoryName
			</div>
             @if (ViewBag.Editable == 1)
             {
                 <div class="edit-link"><a href="/Post/Edit/@Model.PostId"><i style="padding-right:10px;" class="fa fa-pencil-square-o fa-lg"></i>Sửa đổi bài viết</a> </div>
                 
                  <div class="delete-link"><a href="/Post/Delete/@Model.PostId"><i style="padding-right:10px;" class="fa fa-times fa-lg"></i>Xóa bài viết</a> </div>
                    
             }
		    <div class="related-links">
			    <a href="#"> << Trở về </a>
			    <a href="#"> Kế tiếp >> </a>
		    </div>				
	    </div>
@{string[] image_link = Model.PostImages.Select(t => t.ImageURL).ToArray();}
@ViewsUtilities.ProductImages(image_link)
        <div id="post-detail-short">
            <h2>@Model.Title</h2>
            
            @ViewsUtilities.FacebookLike(product_link)
            <span>
                @Model.ShortDescription
            </span>

            <div class="short-detail-attribute">
				<div id="detail-price">
					<p> Giá: </p>
					<h2>@Model.Price</h2>
				</div>
				<div id="hit-count">
					<i class="fa fa-check fa-4x"></i>
					<span> 
						<h2> @Model.HitCount </h2>
						<p>đã xem</p>
					</span>
				</div>
			</div><!-- short-detail-attribute -->
        </div><!-- post-detail-short -->

        <div class="clear"></div>

        <div id="post-detail-full">
            <div class="text-content">
				<span>@Html.Raw(Model.Detail)</span>
            </div>
            @ViewsUtilities.FacebookComment(product_link)
        </div><!-- end of post-detail-full -->

    </div><!-- end of show-post-detail -->
</div><!-- end of main-content -->
            <div class="adswrapper">
				<div class="module">
					<div class="module-header">
						<p>Tin được đăng bởi</p>
					</div>
					<div class="module-detail-wrapper">
						<span class="caption-medium">@(Model.UserProfile.FullName!=null?Model.UserProfile.FullName:Model.UserProfile.UserName)</span>
						<div class="clear"></div>
                        @if(Model.UserProfile.UserType==1) //doanh nghiep
                        {
						        <img class="thumbnail-64" src="/Content/Upload/Images/@Model.UserProfile.LogoImage" />
						        <div class="slogan-owner">
							        <p><em>@Model.UserProfile.Slogan</em></p>
						        </div>
						
						        <div class="clear"></div>
						        <div class="rating">
							        <span> Đánh giá: </span>
							        <div class="rating-stars">
								        <img src="/Content/Upload/Images/star.png"/>
								        <img src="/Content/Upload/Images/star.png"/>
								        <img src="/Content/Upload/Images/star.png"/>
								        <img src="/Content/Upload/Images/star.png"/>
							        </div>
						        </div>
						        <div class="clear"></div>
						        <div class="owner-contact">
							        <span>Liên hệ</span>
							        <a href="/UserProfile/Details/@Model.UserId">Ghé thăm</a>
							        <div class="clear"></div>
						        </div>
						
						        <div class="owner-contact-detail">
							        <i class="fa fa-home fa-lg"></i> <span> Địa chỉ: @Model.UserProfile.Address </span>
							        <div class="clear"></div>
							        <i class="fa fa-phone fa-lg"></i> <span> Tel: @Model.UserProfile.Phone </span>
							        <div class="clear"></div>
							        <i class="fa fa-envelope fa-lg"></i><span> Email: <a href="mailto:@Model.UserProfile.Email">@Model.UserProfile.Email</a></span>
							        <div class="clear"></div>
						        </div>
						}
					</div><!-- end of module-detail-wrappe -->
				</div><!-- end of module -->
				<div class="ads">
					Quảng Cáo
				</div>
			</div><!-- end of adswrapper -->

WebRaoVat/WebRaoVat/Views/Post/Index.cshtml
@model IEnumerable<WebRaoVat.Models.Post>
@* function tao link cho viec sap xep tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper sortLink(string name, int id)
{  
  @* <a href="@Url.Action("Index", "Post", new { CatId= ViewBag.CatId, SortBy = id, PageSize= ViewBag.PageSize,Search=ViewBag.Search, IsAsc = (id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower() })">@name</a> *@
  @:  <option value="/Post/?CatId=@ViewBag.CatId&SorBy=@id&PageSize=@ViewBag.PageSize&Search=@ViewBag.Search&IsAsc=@((id == ViewBag.SortBy ? !@ViewBag.IsAsc : @ViewBag.IsAsc).ToString().ToLower())">@name</option>
}
@* function tao link cho viec phan trang, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper buildLinks(int start, int end, string innerContent)
{
     for (int i = start; i <= end; i++)
     {
         <a class="@(i == ViewBag.CurrentPage ? "current" : "")" href="@Url.Action("Index", "Post", new { SortBy =ViewBag.SortBy, PageSize= ViewBag.PageSize, IsAsc=ViewBag.IsAsc, Search=ViewBag.Search ,page = i })">@(innerContent ?? i.ToString())</a>  
     }
     
}
@* function hien thi pagelink hop ly khi co qua nhieu trang vd 1.....5.current.7....100, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper pageLinks()
{  
    const int maxPages = 11;
     
    if (ViewBag.TotalPages <= maxPages)
    {
        @buildLinks(1, (int)ViewBag.TotalPages, null)
        return;
    }
 
    int pagesAfter = ViewBag.TotalPages - ViewBag.CurrentPage; // Number of pages after current
    int pagesBefore = ViewBag.CurrentPage - 1; // Number of pages before current
 
    if (pagesAfter <= 4)
    {
        @buildLinks(1, 1, null) // Show 1st page
 
        int pageSubset = ViewBag.TotalPages - maxPages - 1 > 1 ? ViewBag.TotalPages - maxPages - 1 : 2;
        @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
        @buildLinks(ViewBag.TotalPages - maxPages + 3, ViewBag.TotalPages, null) // Show last pages
 
        return; // Exit
    }
 
    if (pagesBefore <= 4)
    {
       @buildLinks(1, maxPages - 2, null) // Show 1st pages
 
 
       int pageSubset = maxPages + 2 < ViewBag.TotalPages ? maxPages + 2 : ViewBag.TotalPages - 1;
       @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
       @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
 
        return; // Exit
 
    }
 
    if (pagesAfter > 4)
    {
        @buildLinks(1, 1, null) // Show 1st pages
 
        int pageSubset1 = ViewBag.CurrentPage - 7 > 1 ? ViewBag.CurrentPage - 7 : 2;
        int pageSubset2 = ViewBag.CurrentPage + 7 < ViewBag.TotalPages ? ViewBag.CurrentPage + 7 : ViewBag.TotalPages - 1;
 
        @buildLinks(pageSubset1, pageSubset1, pageSubset1 == ViewBag.CurrentPage - 4 ? null : "...") // Show 1st page subset (...)
 
        @buildLinks(ViewBag.CurrentPage - 3, ViewBag.CurrentPage + 3, null) // Show middle pages
         // Show 2nd page subset (...)
        // only show ... if page is contigous to the previous one.
        @buildLinks(pageSubset2, pageSubset2, pageSubset2 ==  ViewBag.CurrentPage + 4 ? null : "...")
        @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
         return; // Exit
 
    }    
}


@{
    ViewBag.Title = "Details";
}
	<div id="main-content">
				<div class="show-posts">
					<div class= "show-posts-header">
						<div class="category-header">
							Tất cả tin rao
						</div>
						<div class="sort-posts">
							<span>Sắp xếp theo:</span>
							<select onchange="if (this.selectedIndex) {location = this.options[this.selectedIndex].value;}">
                                @sortLink("Thông thường", 0);
                                @sortLink("Tiêu đề", 1);
                                @sortLink("Ngày tạo", 2);
                                @sortLink("Lượt xem", 3);
                                @sortLink("Giá", 4);
							</select>
						</div>
					</div> <!--end of show-posts-header-->
                    @foreach (var item in Model) 
                    {
                         <a href="/Post/Details?id=@item.PostId">

                           <div class="post-item">

                               <div class="post-content-wrapper @(item.PostType==1?"vip": "") ">

                                   <div class="post-header">
                                       @item.Title
                                  </div>
                                  <div class="clear"></div>
					                    	<img src="/Content/Upload/Images/@item.Thumbnail" class="post-image"/>
                                   <div class="post-description-wrapper">
                                       <div class="post-content">
                                           @item.ShortDescription
                                       </div>
                                       <div class = "clear"></div>	
                                       <div class="description-i">
								            <span class="description-i-caption">
									            Giá:
								            </span>
								            <span class="description-i-value">
									            @(item.Price==null ? "Thỏa Thuận" : item.Price)
								            </span>
                                        </div><!-- end of description-i -->
                                        <div class="description-i">
								            <span class="description-i-caption">
									            Quận/Huyện:
								            </span>
								            <span class="description-i-value">
									            @item.Zone.ZoneName
								            </span>									
							            </div><!-- end of description-i -->
						            	<!--date-->
							            <span class="published-date">
								            @(item.Created==null? "1/1/2001": item.Created.Value.ToString("dd/MM/yyyy"))
							            </span>


							            
                                   </div><!-- end of post-description-wrapper -->
                               </div><!-- end of post-content-wrapper -->


                            </div> <!--end of postitem-->

                    </a>
                           
                }
        </div> <!--end of show-postsr-->
<div class="pagination">
Trang: @pageLinks()       
</div>
</div> <!--end of main-content-->
		<div class="adswrapper">
			<div class="ads">
					Quảng Cáo
			</div>
		</div>


			<div id="footer" style="margin-left:10px;">	
				"Copyright 2015"
			</div>