WebRaoVat/WebRaoVat/Models/UserProfile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Posts = new HashSet<Post>();
            this.PostCategories = new HashSet<PostCategory>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<int> UserType { get; set; }
        public string BannerImage { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Review { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string Yahoo { get; set; }
        public string Skype { get; set; }
        public string HotLine { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> NumPosts { get; set; }
        public string Slogan { get; set; }
        public string LogoImage { get; set; }
        public string CustomAds { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostCategory> PostCategories { get; set; }
    }
}

WebRaoVat/WebRaoVat/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using WebMatrix.WebData;
using System.Web.Mvc;
using WebRaoVat.Models;
using WebRaoVat.Filters;

namespace WebRaoVat.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class UserProfileController : Controller
    {
        private raovat_dbEntities db = new raovat_dbEntities();

        //
        // GET: /UserProfile/5

        public ActionResult Index()
        {
            int CurrentId = WebSecurity.CurrentUserId; // >=0 if exist; -1 if anonymous user

            return RedirectToAction("Details");
            
        }

        //
        // GET: /UserProfile/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = -1, int page = 1, int PageSize = 5)
        {
            if(id<0)
                id = WebSecurity.CurrentUserId;
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            db.Entry(userprofile).State = EntityState.Modified;
            userprofile.HitCount = ((userprofile.HitCount != null) ? userprofile.HitCount + 1 : 1);
            db.SaveChanges();

            ViewBag.CurrentPage = page;
            ViewBag.PageSize = PageSize;
            ViewBag.id = id;
            ViewBag.TotalPages = (int)Math.Ceiling((double)userprofile.Posts.Count() / PageSize);
            userprofile.Posts = userprofile.Posts.Skip((page - 1) * PageSize).Take(PageSize).ToList();


            return View(userprofile);
        }

        //User profile is created in AccountController, no need for recreating here
        //
        // GET: /UserProfile/Create
/*
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /UserProfile/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }
*/
        // upgrade user, can be done with admin or user
        // GET: /UserProfile/Upgrade/
        public ActionResult Upgrade(int id =-1)
        {
            if(id<0)
                id = WebSecurity.CurrentUserId;
            
            UserProfile userprofile = db.UserProfiles.Find(id);
            userprofile.UserType = (int) UserType.DoanhNghiep; //0: canhan, 1 doanh nghiep
            db.Entry(userprofile).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Edit");
        }



        //
        // GET: /UserProfile/Edit/

        public ActionResult Edit()
        {
            int id = WebSecurity.CurrentUserId;
            UserProfile userprofile = db.UserProfiles.Find(id);
              if (userprofile == null)
              {
                  return HttpNotFound();
              }
        /*      if (userprofile.UserType == UserType.KhachHangCaNhan.ToString())
                  ViewBag.UserType=userprofile.UserType
              else
                  return DoanhNghiep(userprofile);*/
              List<string> ImagesCollection = new List<string>();
              ImagesCollection.Add(userprofile.LogoImage);
              ImagesCollection.Add(userprofile.BannerImage);
              ViewBag.Images = ImagesCollection.ToArray();
              return View(userprofile);
        }

        //
        // POST: /UserProfile/Edit/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            int CurrentId = WebSecurity.CurrentUserId;
            if (CurrentId != userprofile.UserId)
               return HttpNotFound();

            string[] images_links = null;
            if (Request["images"] != null)
                images_links = Request["images"].ToString().Split(':');
/* Check valid by javascript client side. better than this one
            if (ModelState.IsValid)
            {
            */
            if (images_links.Length ==2)
            {
                if (!String.IsNullOrEmpty(images_links[0]))
                    userprofile.LogoImage = images_links[0];

                if (!String.IsNullOrEmpty(images_links[1]))
                    userprofile.BannerImage = images_links[1];
            }
            else if (images_links.Length == 1)
            {
                if (!String.IsNullOrEmpty(images_links[0]))
                    userprofile.LogoImage = images_links[0];
            }

                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
              //  return HttpNotFound();
                return RedirectToAction("Details");
  /*          }

            return View(userprofile);*/
        }

        //
        // GET: /UserProfile/Delete/5

        public ActionResult Delete(int id = 0)
        {
            id = WebSecurity.CurrentUserId;

            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /UserProfile/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        public enum UserType
        {
            KhachHangCaNhan,
            DoanhNghiep
        }
    }
}

WebRaoVat/WebRaoVat/Views/UserProfile/Create.cshtml
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserProfile</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserId)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserType)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserType)
            @Html.ValidationMessageFor(model => model.UserType)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BannerImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BannerImage)
            @Html.ValidationMessageFor(model => model.BannerImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Fax)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Fax)
            @Html.ValidationMessageFor(model => model.Fax)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Website)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Website)
            @Html.ValidationMessageFor(model => model.Website)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Review)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Review)
            @Html.ValidationMessageFor(model => model.Review)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Yahoo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Yahoo)
            @Html.ValidationMessageFor(model => model.Yahoo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Skype)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Skype)
            @Html.ValidationMessageFor(model => model.Skype)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HotLine)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HotLine)
            @Html.ValidationMessageFor(model => model.HotLine)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HitCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HitCount)
            @Html.ValidationMessageFor(model => model.HitCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NumPosts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NumPosts)
            @Html.ValidationMessageFor(model => model.NumPosts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Slogan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Slogan)
            @Html.ValidationMessageFor(model => model.Slogan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LogoImage)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LogoImage)
            @Html.ValidationMessageFor(model => model.LogoImage)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomAds)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomAds)
            @Html.ValidationMessageFor(model => model.CustomAds)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebRaoVat/WebRaoVat/Views/UserProfile/Delete.cshtml
@model WebRaoVat.Models.UserProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>UserProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserType)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserType)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BannerImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BannerImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fax)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Website)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Website)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Review)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Review)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Rating)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Yahoo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Yahoo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Skype)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Skype)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HotLine)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HotLine)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HitCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HitCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NumPosts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NumPosts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Slogan)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Slogan)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LogoImage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LogoImage)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CustomAds)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomAds)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebRaoVat/WebRaoVat/Views/UserProfile/Details.cshtml
@model WebRaoVat.Models.UserProfile
@* function tao link cho viec phan trang, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper buildLinks(int start, int end, string innerContent)
{
     for (int i = start; i <= end; i++)
     {
         <a class="@(i == ViewBag.CurrentPage ? "current" : "")" href="@Url.Action("Details", "UserProfile", new {id=ViewBag.id, PageSize= ViewBag.PageSize, page = i })">@(innerContent ?? i.ToString())</a>  
     }
     
}
@* function hien thi pagelink hop ly khi co qua nhieu trang vd 1.....5.current.7....100, tham khao http://afana.me/post/paging-sorting-and-searching-ef-cf-and-mvc.aspx *@
@helper pageLinks()
{  
    const int maxPages = 11;
     
    if (ViewBag.TotalPages <= maxPages)
    {
        @buildLinks(1, (int)ViewBag.TotalPages, null)
        return;
    }
 
    int pagesAfter = ViewBag.TotalPages - ViewBag.CurrentPage; // Number of pages after current
    int pagesBefore = ViewBag.CurrentPage - 1; // Number of pages before current
 
    if (pagesAfter <= 4)
    {
        @buildLinks(1, 1, null) // Show 1st page
 
        int pageSubset = ViewBag.TotalPages - maxPages - 1 > 1 ? ViewBag.TotalPages - maxPages - 1 : 2;
        @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
        @buildLinks(ViewBag.TotalPages - maxPages + 3, ViewBag.TotalPages, null) // Show last pages
 
        return; // Exit
    }
 
    if (pagesBefore <= 4)
    {
       @buildLinks(1, maxPages - 2, null) // Show 1st pages
 
 
       int pageSubset = maxPages + 2 < ViewBag.TotalPages ? maxPages + 2 : ViewBag.TotalPages - 1;
       @buildLinks(pageSubset, pageSubset, "...") // Show page subset (...)
 
       @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
 
        return; // Exit
 
    }
 
    if (pagesAfter > 4)
    {
        @buildLinks(1, 1, null) // Show 1st pages
 
        int pageSubset1 = ViewBag.CurrentPage - 7 > 1 ? ViewBag.CurrentPage - 7 : 2;
        int pageSubset2 = ViewBag.CurrentPage + 7 < ViewBag.TotalPages ? ViewBag.CurrentPage + 7 : ViewBag.TotalPages - 1;
 
        @buildLinks(pageSubset1, pageSubset1, pageSubset1 == ViewBag.CurrentPage - 4 ? null : "...") // Show 1st page subset (...)
 
        @buildLinks(ViewBag.CurrentPage - 3, ViewBag.CurrentPage + 3, null) // Show middle pages
         // Show 2nd page subset (...)
        // only show ... if page is contigous to the previous one.
        @buildLinks(pageSubset2, pageSubset2, pageSubset2 ==  ViewBag.CurrentPage + 4 ? null : "...")
        @buildLinks(ViewBag.TotalPages, ViewBag.TotalPages, null) // Show last page
         return; // Exit
 
    }    
}


@{
    ViewBag.Title = "Details";
}

<div id="main-content">
		<div id="show-post-detail">
					<div class= "post-detail-header">
						<div class="category-header">
							Thông tin doanh nghiệp
						</div>
						<div class="related-links">
							<a href="#"> << Trở về </a>
						</div>
						
					</div>
					<div id="user-banner">
						@ViewsUtilities.ImageLink(Model.BannerImage)
						<span>@Model.FullName</span>
					</div>
					<div class="social-like-share">
					    <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
					</div>
					
					<div class="clear"></div>
			<div class="modules-wrapper">
				<div class="module">
					<div class="module-header">
						<p>Thông tin chi tiết</p>
					</div>
					<div class="module-detail-wrapper">
					
						<div class="owner-contact-detail">
						
							<i class="fa fa-home fa-lg"></i> <span> <strong> Địa chỉ: </strong>@Model.Address</span>
							<div class="clear"></div>
							
					@if (Model.Phone != null && Model.Phone != "")
                    {
                        <i class="fa fa-phone fa-lg"></i> <span> <strong> Tel: </strong>@Model.Phone</span>
                    }
							<div class="clear"></div>
					@if (Model.Fax != null && Model.Fax != "")
                    {
							<i class="fa fa-fax fa-lg"></i> <span> <strong> Fax: </strong>@Model.Fax </span>
							<div class="clear"></div>
                    }		
							<i class="fa fa-globe fa-lg"></i> <span> <strong> Website: </strong><a href="@Model.Website">@Model.Website</a></span>
							<div class="clear"></div>
														
					@if (Model.Email != null && Model.Email != "")
                    {
							<i class="fa fa-envelope fa-lg"></i><span> <strong> Email: </strong><a href="mailto:@Model.Email">@Model.Email</a></span>
							<div class="clear"></div>
                    }
						</div>

							<div class="review-rating">
							 <span>Review:</span>
								<div class="progress">
										<span class="percent">30%</span>
								<div class="bar" style="width:30%;"></div>
								</div>
							</div>
							
							<div class="clear"></div>
							
							<div class="review-rating">
							 <span>Rating:</span>
								<div class="progress">
										<span class="percent">60%</span>
								<div class="bar" style="width:60%;"></div>
								</div>
							</div>

						
						
					</div>
				</div>
				
				<div class="module">
					<div class="module-header">
						<p>Hỗ trợ</p>
					</div>
					<div class="support-contact">
                         <p></p>
					@if (Model.HotLine!=null && Model.HotLine!=""){	<span>Hotline: @Model.HotLine</span>}
					@if (Model.Yahoo!=null && Model.Yahoo!=""){
						<span>Chat Online:</span>
						<span class="yahoo-contact">
							<a href = "ymsgr:sendim?@Model.Yahoo">
									<img border=0 src="http://opi.yahoo.com/online?u=@(Model.Yahoo)&m=g&t=2"/>
							</a>
						</span>
					}
					@if (Model.Skype!=null && Model.Skype!=""){
						<span class="skype-contact">
							<a href="skype:@Model.Skype?chat">
								<img border=0 src="http://mystatus.skype.com/@Model.Skype"/>
							</a>
						</span>
					}
					</div>
				</div>


				<div class="module">
					<div class="module-header">
						<p>Thống kê</p>
					</div>
					<div class="support-contact">
                        <p></p>
						<span style="width: 220px">Lượng truy cập: @Model.HitCount</span>
						<br />
						<span>Tin post: @Model.Posts.Count</span>
						<p></p>
					</div>
				</div>				

			
			</div>		<!-- end of modules-wrapper-->	
        </div><!-- end show-post-detail-->	
	

    <div class="small-posts">
			
				<div class="show-posts">
						<div class= "show-posts-header">
							<div class="category-header">
								Các tin đã đăng
							</div>						
						</div>
				@foreach (var item in Model.Posts) 
                {
                  <a href="/Post/Details?id=@item.PostId">	
					<div class="post-item ">
                        <div class="post-content-wrapper @(item.PostType==1?"vip": "") ">
                            <div class="post-header" style="width: 500px">
								@item.Title
							</div>
							<div class="clear"></div>
							<img src="/Content/Upload/Images/@item.Thumbnail" class="post-image">
							<div class="post-description-wrapper">
							
								<div class="post-content">
										@item.ShortDescription
								</div>				

								<div class = "clear"></div>						

								<div class="description-i">
									<span class="description-i-caption">
										Giá:
									</span>
									<span class="description-i-value">
										@item.Price
									</span>
								</div>
								<div class="description-i">
									<span class="description-i-caption">
										Quận/Huyện:
									</span>
									<span class="description-i-value">
										@item.Zone.ZoneName
									</span>									
								</div>
								<!--date-->					
							    <span class="published-date">
								    @(item.Created==null? "1/1/2001": item.Created.Value.ToString("dd/MM/yyyy"))
							    </span>


							            
                         </div><!-- end of post-description-wrapper -->
                    </div><!-- end of post-content-wrapper -->
				</div><!--post-item-->
            </a>
      }

        </div><!--show-posts-->
        <div class="pagination">
            Trang: @pageLinks()       
        </div>
    </div><!--small-posts-->

    </div><!-- end main content-->

			<div class="adswrapper">
				<div class="ads">
					Quảng Cáo
				</div>
			</div>


			<div id="footer" style="margin-left:10px;">	
				<div class="footer_container">
					<div class="addr_footer">
						<span class="footer_head">Liên hệ</span>
							<a>Địa chỉ: Hòa Thành, Tây Ninh</a>
							<a>Số điện thoại: 0123456789</a>
					</div>
					<div class="info_footer">
						<span class="footer_head">Thông tin cho bạn</span>
							<a href="http://www.nhanh60s.vn/">Quy định đăng tin</a>
							<a href="http://www.nhanh60s.vn/">Điều khoản</a>
							<a href="http://www.nhanh60s.vn/">Chính sách</a>
							<a href="http://www.nhanh60s.vn" >Kinh nghiệm đăng tin</a>
					</div>
					<div class="about_footer">
						<span class="footer_head">Về chúng tôi</span>
							<a href="http://www.nhanh60s.vn/">Giới thiệu</a>
							<a href="http://www.nhanh60s.vn/">Mục tiêu</a>
							<a href="http://www.nhanh60s.vn/tuyendung">Tuyển dụng</a>
					</div>
					
					<div class="register_footer">
						<span class="footer_head">Chứng nhận</span>
						<a href="http://online.gov.vn/HomePage/" target="_blank">
							<img class="bct" src="/Content/bct.png">
						</a>
					</div>
					
					<div class="clear_float"></div>
				</div>
				<hr>
					<p style="color: #808080;">
						Bản quyền của <a href="http://Nhanh60s.vn" style="color: #66FFCC">Nhanh60s</a> |  WWW.NHANH60S.VN © 2015  </p>
			</div>